name: Run Daily Report Global
on:
  schedule:
    - cron: "0 4 * * *" # Run every day at 4 UTC
  # push:
  #   branches:
  #     - master
jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: 3.11

      - name: Install Osmium
        run: sudo apt-get install -y osmium-tool

      - name: Install necessary dependecies
        run: |
          pip install flare-floss
          python setup.py install 
          pip install tweepy
          pip install -r requirements.txt

      - name: Generate Daily Stats
        env: #assign variables
          OSM_USERNAME: ${{ secrets.OSM_USERNAME }}
          OSM_PASSWORD: ${{ secrets.OSM_PASSWORD }}
        run: |
          osmsg  --url "https://planet.openstreetmap.org/replication/day" --format csv image --last_day --tags 'building' 'highway' 'waterway' 'amenity' --name stats/Global/Daily/stats --all_tags --read_from_metadata stats/Global/Daily/stats_metadata.json --changeset --summary --charts  --meta --force

      - name: add stats to git
        continue-on-error: true

        run: |
          git pull
          git config --global user.email "skshitizraj@gmail.com"
          git config --global user.name "kshitijrajsharma"
          base_dir=stats/Global/Daily

          mkdir -p $base_dir
          mv $base_dir/stats_summary.md $base_dir/Readme.md
          git add -f $base_dir/*

          git commit -m "Updated Daily global stats"
          git push

      - name: Tweet Stats
        continue-on-error: true
        env: #assign variables
          API_KEY: ${{ secrets.API_KEY }}
          API_KEY_SECRET: ${{ secrets.API_KEY_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
        run: |
          commit_id=$(git rev-parse --short HEAD)
          python tweet.py --git $commit_id --name stats/Global/Daily/stats --tweet 'OSM Last Day' --mention '@openstreetmap'
